apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: PUERTO-DIGITAL-rollout
  namespace: dev
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
        - setWeight: 50
        - pause: { duration: 2m }
        - setWeight: 100
  selector:
    matchLabels:
      app: PUERTO-DIGITAL
  template:
    metadata:
      labels:
        app: PUERTO-DIGITAL
    spec:
      containers:
        - name: PUERTO-DIGITAL
          image: docker.io/PUERTO-DIGITAL:latest
          ports:
            - containerPort: 8080