apiVersion: apps/v1
kind: Deployment
metadata:
  name: PUERTO-DIGITAL-app
  namespace: dev
  labels:
    app: PUERTO-DIGITAL
spec:
  replicas: 3
  selector:
    matchLabels:
      app: PUERTO-DIGITAL
  template:
    metadata:
      labels:
        app: PUERTO-DIGITAL
    spec:
      containers:
        - name: PUERTO-DIGITAL
          image: docker.io/PUERTO-DIGITAL-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: PUERTO-DIGITAL-secrets
                  key: api-key
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20