groups:
  - name: porttrack-alerts
    rules:
      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Alta latencia en servicios de PortTrack"

      - alert: CPUOverload
        expr: rate(container_cpu_usage_seconds_total{container=~"porttrack-.*"}[1m]) > 0.85
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Uso de CPU elevado en contenedores PortTrack"